version: "3.3"

services:
  db:
    container_name: 'local-wordpress-db'
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3333:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: 'local-wordpress'
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - /home/muhammad/sites/wp-plugins/daily-prayer-time-for-mosques/trunk/:/var/www/html/wp-content/plugins/dpt
    ports:
      - "8888:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  mysql_data: {}
